spring.application.name=authservice
server.port=9000

logging.level.org.springframework.security=WARN
logging.level.org.springframework.security.oauth2=WARN
logging.level.org.springframework.security.web=WARN
logging.level.org.springframework.security.oauth2.server.authorization=WARN

auth.redirect-uri=${AUTH_REDIRECT_URI:http://localhost:8080/login/oauth2/code/authservice}
auth.issuer=${AUTH_ISSUER_URI:http://127.0.0.1:9000}
