spring.application.name=messageservice
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:9000
server.port=8082

spring.grpc.client.default-channel.address=localhost:8081
spring.grpc.client.default-channel.secure=false
spring.grpc.client.default-channel.negotiation-type=plaintext

spring.datasource.url=jdbc:postgresql://localhost:5455/${MESSAGE_POSTGRES_DB}
spring.datasource.username=${MESSAGE_POSTGRES_USER}
spring.datasource.password=${MESSAGE_POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
