spring.application.name=bff

app.services.user-url=${USER_SERVICE_URL:http://localhost:8081}
app.services.message-url=${MESSAGE_SERVICE_URL:http://localhost:8082}

spring.security.oauth2.client.provider.authservice.issuer-uri=${AUTH_ISSUER_URI:http://127.0.0.1:9000}
spring.security.oauth2.client.registration.authservice.client-id=${AUTH_CLIENT_ID:gateway-client}
spring.security.oauth2.client.registration.authservice.client-secret=${AUTH_CLIENT_SECRET:secret}
spring.security.oauth2.client.registration.authservice.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.authservice.redirect-uri=${AUTH_REDIRECT_URI:{baseUrl}/login/oauth2/code/{registrationId}}
spring.security.oauth2.client.registration.authservice.scope=user.read,openid

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_ISSUER_URI:http://127.0.0.1:9000}

spring.graphql.graphiql.enabled=true
