name: CI Pipeline

on:
  push:
    branches: [ main, develop, feat/integration ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [authservice, userservice, messageservice, bff, cli]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'

      - name: Make Maven wrapper executable
        working-directory: ${{ matrix.service }}
        run: chmod +x ./mvnw

      - name: Build and test ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: ./mvnw clean verify
